return {
  {
    "catppuccin/nvim",
    enabled = true,
    opts = {
      color_overrides = {
        all = {},
        latte = {},
        frappe = {},
        macchiato = {},
        mocha = {},
      },
      custom_highlights = function(colors)
        return {
          TreesitterContext = { bg = colors.mantle },
          TreesitterContextLineNumber = { bg = colors.mantle, fg = colors.red },
          TreesitterContextBottom = { style = {} },
          VertSplit = { fg = colors.mantle, bg = colors.mantle },
          MiniTrailspace = { bg = colors.red },
          FlashCurrent = { bg = colors.peach, fg = colors.base },
          FlashLabel = { bg = colors.red, bold = true, fg = colors.base },
          FlashMatch = { bg = colors.blue, fg = colors.base },
          FlashCursor = { reverse = true },
          NeoTreeWinSeparator = { fg = colors.mantle, bg = colors.mantle },
          WinSeparator = { fg = colors.mantle, bg = colors.mantle },
          EdgyNormal = { bg = colors.mantle },
          EdgyWinBar = { fg = colors.subtext0, bg = colors.mantle, bold = true },
          EdgyWinBarNC = { fg = colors.overlay0, bg = colors.mantle },
          EdgyTitle = { fg = colors.subtext0, bg = colors.mantle, bold = true },
          EdgyIcon = { fg = colors.blue, bg = colors.mantle },
          EdgyIconActive = { fg = colors.peach, bg = colors.mantle },
          CursorLineNr = { fg = colors.peach },
          MiniCursorword = { bg = "#45475a", style = {} },
          MiniCursorwordCurrent = { bg = "#45475a", style = {} },
          DiagnosticError = { style = {} },
          DiagnosticWarn = { style = {} },
          DiagnosticInfo = { style = {} },
          DiagnosticHint = { style = {} },
          DiagnosticOk = { style = {} },
          Comment = { fg = colors.surface2, style = { "italic" } },
          ["@comment"] = { fg = colors.surface2, style = { "italic" } },
          NoiceCmdlineIcon = { style = {} },
        }
      end,
    },
  },
}
